/*
 * Contract Gen runtime grammar, originally generated by Xtext 2.38.0.
 *
 * REMODEL's model and operation-contract wrappers are project extensions. The
 * embedded expression language is an intentionally bounded, executable subset
 * of OCL 2.4: every accepted expression form must have a corresponding
 * ContractToTypescript lowering. The standard allInstances() spelling is used
 * for generation; allInstance() is retained only to read historical artifacts.
 */
grammar REMODEL;

// Rule RequirementModel
ruleRequirementModel:
	('RequirementsModel::' ruleSimpleNameCS)? (
		'@Description(' RULE_DOUBLE_QUOTED_STRING ')'
	)? ruleUseCaseModel ruleDomainModel;

// Rule Interaction
ruleInteraction:
	'Interaction' ruleSimpleNameCS '{' '[Participants:' RULE_ID* ']' ruleMessage* ruleExecution*
		ruleCombinedFragment* ruleAbstractEnd* '}';

// Rule Message
ruleMessage: ( ruleCallMessage | ruleReturnMessage);

// Rule CallMessage
ruleCallMessage:
	'CallMessage::' ruleSimpleNameCS '(' RULE_ID RULE_ID '->' RULE_ID ')';

// Rule ReturnMessage
ruleReturnMessage:
	'ReturnMessage::' ruleSimpleNameCS '(' RULE_ID '->' RULE_ID RULE_ID ')';

// Rule Execution
ruleExecution:
	'Execution::' ruleSimpleNameCS '(' RULE_ID RULE_ID RULE_ID ')';

// Rule CombinedFragment
ruleCombinedFragment:
	'CombinedFragment::' ruleSimpleNameCS '->' ruleOperator '{' '[Participants:' RULE_ID* ']'
		RULE_ID '->' RULE_ID ruleOperand* '}';

// Rule Operator
ruleOperator: ( 'loop' | 'alt' | 'option');

// Rule Operand
ruleOperand:
	'Operand::' ruleSimpleNameCS '(' RULE_ID RULE_ID ')';

// Rule AbstractEnd
ruleAbstractEnd: ( ruleMixEnd | ruleMixOpAndCFEnd);

// Rule MixEnd
ruleMixEnd: ( ruleExecutionEnd | ruleMessageEnd);

// Rule MixOpAndCFEnd
ruleMixOpAndCFEnd: ( ruleCombinedFragmentEnd | ruleOperandEnd);

// Rule MessageEnd
ruleMessageEnd:
	'MessageEnd::' ruleSimpleNameCS '(' RULE_ID RULE_ID ')';

// Rule ExecutionEnd
ruleExecutionEnd:
	'ExecutionEnd::' ruleSimpleNameCS '(' RULE_ID RULE_ID ')';

// Rule CombinedFragmentEnd
ruleCombinedFragmentEnd:
	'CombinedFragmentEnd::' ruleSimpleNameCS '(' RULE_ID ')';

// Rule OperandEnd
ruleOperandEnd: 'OperandEnd::' ruleSimpleNameCS '(' RULE_ID ')';

// Rule DomainModel
ruleDomainModel:
	'DomainModel' ruleSimpleNameCS (
		'(' RULE_DOUBLE_QUOTED_STRING ')'
	)? '{' ruleEntity* '}';

// Rule UseCaseModel
ruleUseCaseModel:
	'UseCaseModel' ruleSimpleNameCS (
		'(' RULE_DOUBLE_QUOTED_STRING ')'
	)? '{' ruleUC* ruleActor* ruleInteraction* ruleService* ruleContract* '}';

// Rule Actor
ruleActor:
	'Actor' ruleSimpleNameCS ('(' RULE_DOUBLE_QUOTED_STRING ')')? (
		'extends' RULE_ID
	)? '{' ('@Description(' RULE_DOUBLE_QUOTED_STRING ')')? RULE_ID* '}';

// Rule UC
ruleUC:
	'UC' '::' ruleSimpleNameCS '('? RULE_DOUBLE_QUOTED_STRING? ')'? (
		ruleUSECASE_RELATION RULE_ID (',' RULE_ID)*
	)? ('definedBySSD' '(' RULE_ID ( ',' RULE_ID)* ')')? (
		'relatedService' '(' RULE_ID (',' RULE_ID)* ')'
	)? ('@Description(' RULE_DOUBLE_QUOTED_STRING ')')?;

// Rule Service
ruleService:
	'Service' ruleSimpleNameCS '{' (
		'@Description(' RULE_DOUBLE_QUOTED_STRING ')'
	)? ('[Operation]' ruleOperation*)? (
		'[TempProperty]' ruleAttribute*
	)? ('[WorkFlow]' RULE_ID*)? ('[INV]' ruleInvariance*)? '}';

// Rule Participant
ruleParticipant: ( ruleActor | ruleService);

// Rule Partition
rulePartition: RULE_ID '{' ruleWorkflowExp* '}';

// Rule WorkflowExp
ruleWorkflowExp:
	(
		ruleSimpleOperation
		| ruleComplexOpeartion
		| ruleInitalNode
		| ruleActivityFinal
		| ruleForkNode
		| ruleJoinNode
		| rulePartitionAction
	);

// Rule PartitionAction
rulePartitionAction: '->' RULE_ID ':' RULE_ID;

// Rule ActivityFinal
ruleActivityFinal: 'ActivityFinal';

// Rule InitalNode
ruleInitalNode: 'ActivityStart';

// Rule ForkNode
ruleForkNode: 'ForkNode' '->' '(' RULE_ID+ ')';

// Rule JoinNode
ruleJoinNode: '(' RULE_ID+ ')' '->' 'JoinNode';

// Rule ComplexOpeartion
ruleComplexOpeartion: ( ruleLoopExp | ruleSwitchExp);

// Rule SimpleOperation
ruleSimpleOperation: RULE_ID;

// Rule LoopExp
ruleLoopExp:
	'Loop' '->' ruleSimpleNameCS '{' ruleWorkflowExp* '}';

// Rule SwitchExp
ruleSwitchExp:
	'Switch' '->' ruleSimpleNameCS '{' ruleSwitchCase* ruleSwitchDefault? '}';

// Rule SwitchCase
ruleSwitchCase:
	'case:' ruleSimpleNameCS '->' ruleSimpleOperation;

// Rule SwitchDefault
ruleSwitchDefault: 'default:' ruleSimpleOperation;

// Rule Operation
ruleOperation:
	ruleOperationName '(' ruleParameter? (',' ruleParameter)* ')' (
		':' ruleTypeCS
	)?;

// Rule OperationName
ruleOperationName: ruleSimpleNameCS;

// Rule Parameter
ruleParameter: ruleParametersName ( ':' ruleTypeCS)?;

// Rule ParametersName
ruleParametersName: ruleSimpleNameCS;

// Rule Entity
ruleEntity:
	'@AutoCRUD'? 'Entity' ruleSimpleNameCS ('extends' RULE_ID)? '{' (
		'@Description(' RULE_DOUBLE_QUOTED_STRING ')'
	)? ruleAttribute* ('[Refer]' ruleReference*)? (
		'[INV]' ruleInvariance*
	)? '}';

// Rule Attribute
ruleAttribute: ruleSimpleNameCS ':' ruleTypeCS '*'?;

// Rule Reference
ruleReference:
	ruleSimpleNameCS ':' RULE_ID '*'? '!'? '@-'? '*-'? ruleAssociationTypeCS;

// Rule TypeCS
ruleTypeCS:
	(
		ruleEntityType
		| rulePrimitiveTypeCS
		| ruleEnumEntity
		| ruleCollectionTypeCS
	);

// Rule Invariance
ruleInvariance:
	'inv' ruleSimpleNameCS ':' (
		'{' ruleOCLExpressionCS '}'
		| ruleOCLExpressionCS
	) 'ASSOCINV'?;

// Rule EntityType
ruleEntityType: RULE_ID;

// Rule EnumEntity
ruleEnumEntity:
	ruleSimpleNameCS '[' ruleEnumItem ('|' ruleEnumItem)* ']';

// Rule EnumItem
ruleEnumItem: RULE_ID;

// Rule USECASE_RELATION
ruleUSECASE_RELATION: ( 'include' | 'extend');

// Rule Contract
ruleContract:
	'Contract' RULE_ID '::' ruleOperation '{' ruleDefinition? rulePrecondition rulePostcondition '}'
		;

// Standalone entry rules consume the complete input used by the generation and
// validation pipeline. ruleContract itself remains embeddable in a use-case model.
ruleStandaloneContract: ruleContract EOF;
ruleStandaloneDefinition: ruleDefinition EOF;
ruleStandalonePrecondition: rulePrecondition EOF;
ruleStandalonePostcondition: rulePostcondition EOF;

// Rule Definition
ruleDefinition:
	'definition' ':' ruleVariableDeclarationCS (
		',' ruleVariableDeclarationCS
	)*;

// Rule Precondition
rulePrecondition:
	'precondition' ':' (
		ruleOCLExpressionCS
		| '{' ruleOCLExpressionCS '}'
	);

// Rule Postcondition
rulePostcondition:
	'postcondition' ':' (
		ruleOCLExpressionCS
		| '{' ruleOCLExpressionCS '}'
	);

// Rule OCLExpressionCS
ruleOCLExpressionCS:
	(
		ruleLiteralExpCS
		| ruleLetExpCS
		| ruleIfExpCS
		| ruleLogicFormulaExpCS
		| ruleNestedExpCS
	);

// Rule NestedExpCS
ruleNestedExpCS: '(' ruleOCLExpressionCS ')';

// Rule LogicFormulaExpCS
ruleLogicFormulaExpCS:
	ruleAtomicExpression (
		(
			'and' (
				ruleAtomicExpression
				| ruleIfExpCS
				| ruleNestedExpCS
			)
		)+
		| (
			'or' (
				ruleAtomicExpression
				| ruleIfExpCS
				| ruleNestedExpCS
			)
		)+
	)?;

// Rule AtomicExpression
ruleAtomicExpression:
	ruleLeftSubAtomicExpression (
		ruleInfixCompareOperatorName ruleRightSubAtomicExpression (
			ruleInfixOperatorName (
				rulePrimitiveLiteralExpCS
				| ruleAtomicExpression
			)
		)?
	)?;

// Rule LeftSubAtomicExpression
ruleLeftSubAtomicExpression:
	(ruleVariableExpCS | ruleCallExpCS);

// Rule RightSubAtomicExpression
ruleRightSubAtomicExpression:
	(ruleLiteralExpCS | ruleVariableExpCS | ruleCallExpCS);

// Rule InfixCompareOperatorName
ruleInfixCompareOperatorName:
	('>' | '<' | '>=' | '<=' | '=' | '<>');

// Rule InfixOperatorName
ruleInfixOperatorName: ( '*' | '/' | '+' | '-');

// Rule CallExpCS
ruleCallExpCS: ( ruleFeatureCallExpCS | ruleLoopExpCS);

// Rule LoopExpCS
ruleLoopExpCS: ruleIteratorExpCS;

// Rule IteratorExpCS
ruleIteratorExpCS:
	(
		(ruleClassiferCallExpCS | rulePropertyCallExpCS)
		| ruleSimpleNameCS
	) '->' ruleIteratorIdentifier '(' (
		ruleVariableDeclarationCS (',' ruleVariableDeclarationCS)* '|'
	)? (ruleLogicFormulaExpCS | ruleIfExpCS) ')';

// Rule IteratorIdentifier
ruleIteratorIdentifier:
	(
		'one'
		| 'exists'
		| 'select'
		| 'any'
		| 'forAll'
		| 'collect'
		| 'isUnique'
	);

// Rule ArgumentsCS
ruleArgumentsCS: ruleOCLExpressionCS ( ',' ruleArgumentsCS)?;

// Rule FeatureCallExpCS
ruleFeatureCallExpCS:
	(
		rulePropertyCallExpCS
		| ruleClassiferCallExpCS
		| ruleStandardOperationExpCS
		| ruleStandardNavigationCallExpCS
		| ruleOperationCallExpCS
	);

// Rule StandardNavigationCallExpCS
ruleStandardNavigationCallExpCS:
	(
		ruleClassiferCallExpCS
		| rulePropertyCallExpCS
		| ruleSimpleNameCS
	) '->' ruleStandardCollectionOperation;

// Rule StandardOperationExpCS
ruleStandardOperationExpCS:
	ruleVariableExpCS (
		('.' | '->') rulePredefineOp
		| '.' ruleVariableExpCS ruleIsMarkedPreCS? ('.' | '->') rulePredefineOp
	);

// Rule PredefineOp
rulePredefineOp:
	(
		ruleStandardNoneParameterOperation
		| ruleStandardParameterOperation
		| ruleStandardDateOperation
	);

// Rule StandardNoneParameterOperation
ruleStandardNoneParameterOperation:
	(
		'oclIsNew()'
		| 'oclIsUndefined()'
		| 'isEmpty()'
		| 'notEmpty()'
		| 'size()'
		| 'sum()'
	);

// Rule StandardParameterOperation
ruleStandardParameterOperation:
	'oclIsTypeOf' '(' (rulePrimitiveTypeCS | ruleEntityType) ')';

// Rule StandardCollectionOperation
ruleStandardCollectionOperation:
	('includes' | 'excludes' | 'includesAll' | 'excludesAll') '(' ruleSimpleNameCS ')';

// Rule StandardDateOperation
ruleStandardDateOperation:
	('After' | 'Before' | 'isAfter' | 'isBefore' | 'isEqual') '(' (
		ruleSimpleNameCS
		| ruleNumberLiteralExpCS
		| rulePropertyCallExpCS
	) ')' ('.' ruleStandardDateOperation)?;

// Rule ClassiferCallExpCS
ruleClassiferCallExpCS:
	// allInstance() is a parser-only compatibility alias and is not exposed to generation.
	ruleSimpleNameCS '.' ('allInstances()' | 'allInstance()');

// Rule PropertyCallExpCS
rulePropertyCallExpCS:
	ruleVariableExpCS '.' (ruleVariableExpCS '.')? ruleSimpleNameCS ruleIsMarkedPreCS?;

// Rule OperationCallExpCS
ruleOperationCallExpCS:
	ruleSimpleNameCS '(' ruleOperationParameters? (
		',' ruleOperationParameters
	)* ')';

// Rule OperationParameters
ruleOperationParameters:
	(
		ruleSimpleNameCS
		| rulePropertyCallExpCS
		| (RULE_SINGLE_QUOTED_STRING | RULE_DOUBLE_QUOTED_STRING)
	);

// Rule IsMarkedPreCS
ruleIsMarkedPreCS: '@' 'pre';

// Rule VariableExpCS
ruleVariableExpCS: ( 'self' | 'result' | ruleSimpleNameCS);

// Rule SimpleNameCS
ruleSimpleNameCS: RULE_ID;

// Rule IfExpCS
ruleIfExpCS:
	'if' ruleOCLExpressionCS 'then' ruleOCLExpressionCS (
		'else' ruleOCLExpressionCS
	)? 'endif';

// Rule LetExpCS
ruleLetExpCS:
	'let' ruleVariableDeclarationCS (
		',' ruleVariableDeclarationCS
	)* 'in' ruleOCLExpressionCS;

// Rule VariableDeclarationCS
ruleVariableDeclarationCS:
	ruleSimpleNameCS (':' ruleTypeCS)? ('=' ruleOCLExpressionCS)?;

// Rule LiteralExpCS
ruleLiteralExpCS:
	(
		ruleCollectionLiteralExpCS
		| rulePrimitiveLiteralExpCS
		| ruleEnumLiteralExpCS
	);

// Rule EnumLiteralExpCS
ruleEnumLiteralExpCS: ruleSimpleNameCS '::' RULE_ID;

// Rule CollectionTypeCS
ruleCollectionTypeCS:
	ruleCollectionTypeIdentifierCS '(' ruleTypeCS ')';

// Rule CollectionLiteralExpCS
ruleCollectionLiteralExpCS:
	ruleCollectionTypeIdentifierCS '{' ruleCollectionLiteralPartCS? (
		( ',') ruleCollectionLiteralPartCS
	)* '}';

// Rule CollectionLiteralPartCS
ruleCollectionLiteralPartCS:
	(ruleCollectionRangeCS | ( ruleCollectionItem));

// Rule CollectionRangeCS
ruleCollectionRangeCS:
	(ruleOCLExpressionCS) '..' ruleOCLExpressionCS;

// Rule CollectionItem
ruleCollectionItem: ruleOCLExpressionCS;

// Rule PrimitiveLiteralExpCS
rulePrimitiveLiteralExpCS:
	(
		ruleNumberLiteralExpCS
		| ruleStringLiteralExpCS
		| ruleBooleanLiteralExpCS
		| ruleNullLiteralExpCS
	);

// Rule NumberLiteralExpCS
ruleNumberLiteralExpCS:
	(
		ruleIntegerLiteralExpCS
		| ruleRealLiteralExpCS
	);

// Rule IntegerLiteralExpCS
ruleIntegerLiteralExpCS: RULE_INT;

// Rule RealLiteralExpCS
ruleRealLiteralExpCS: ruleFloat;

// Rule BooleanLiteralExpCS
ruleBooleanLiteralExpCS: ( 'true' | 'false');

// Rule StringLiteralExpCS
ruleStringLiteralExpCS:
	(RULE_SINGLE_QUOTED_STRING | RULE_DOUBLE_QUOTED_STRING);

// Rule NullLiteralExpCS
ruleNullLiteralExpCS: 'null';

// Rule Float
ruleFloat: RULE_INT '.' RULE_INT;

// Rule CollectionTypeIdentifierCS
ruleCollectionTypeIdentifierCS: 'Set';

// Rule PrimitiveTypeCS
rulePrimitiveTypeCS:
	(
		'Boolean'
		| 'Integer'
		| 'Real'
		| 'String'
		| 'Date'
	);

// Rule AssociationTypeCS
ruleAssociationTypeCS:
	('Association' | 'Aggregation' | 'Composition');

RULE_DOUBLE_QUOTED_STRING:
	'"' (RULE_ESCAPED_CHARACTER | ~["\\\r\n])* '"';

RULE_SINGLE_QUOTED_STRING:
	'\'' (RULE_ESCAPED_CHARACTER | '\'' '\'' | ~['\\\r\n])* '\'';

fragment RULE_ESCAPED_CHARACTER:
	'\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | '\'' | '\\' | 'u' RULE_HEX RULE_HEX RULE_HEX RULE_HEX);

fragment RULE_HEX: [0-9a-fA-F];

// Reserved OCL words whose runtime semantics are intentionally outside this subset.
// Keeping them out of RULE_ID makes unsupported constructs fail during parsing
// instead of being silently interpreted as model variables or entity types.
UNSUPPORTED_OCL_KEYWORD:
	(
		'invalid'
		| 'OclInvalid'
		| 'UnlimitedNatural'
		| 'Bag'
		| 'Sequence'
		| 'Collection'
		| 'OrderedSet'
		| 'Tuple'
	);

RULE_ID:
	'^'? ('a' ..'z' | 'A' ..'Z' | '_') (
		'a' ..'z'
		| 'A' ..'Z'
		| '_'
		| '0' ..'9'
	)*;

RULE_INT: ('0' ..'9')+;

WS: [ \t\r\n]+ -> skip;

LINE_COMMENT: '//' ~[\r\n]* -> channel(1);
BLOCK_COMMENT: '/*' .*? '*/' -> channel(1);
