import {createEntryCode} from '../src/app/service/createEntryCode';
import {parseTypescriptEntry} from '../src/app/service/parseTypescriptEntry';
import * as AutomatedTellerMachine from '../src/rm2pt/project/AutomatedTellerMachine';
import * as CoCoME from '../src/rm2pt/project/CoCoME';
import * as LibraryManagementSystem from '../src/rm2pt/project/LibraryManagementSystem';

describe('createEntryCode', () => {
  let logSpy: jest.SpyInstance;

  beforeEach(() => {
    logSpy = jest.spyOn(console, 'log').mockImplementation(() => undefined);
  });

  afterEach(() => {
    logSpy.mockRestore();
  });

  test('preserves use-case state variables and exports the generated entry', async () => {
    const operation = CoCoME.useCase.orderProducts.relatedService.operations.find(
      ({name}) => name === 'orderItem'
    )!;
    const generated = await createEntryCode({
      project: 'CoCoME',
      useCase: 'orderProducts',
      operation: operation.name,
      ocl: {
        definition: operation.definition,
        precondition: operation.precondition,
        postcondition: operation.postcondition,
      },
    });

    expect(generated.originalService).toContain('CurrentOrderProduct');
    expect(generated.entry).toMatch(/export\s*\{\s*CoCoMEOrderProducts_AutoGenerated\s*\}/);
    expect(generated.entry).toMatch(/export\s*\{[^}]*Item/);
  });

  test('typechecks numeric @pre subtraction on an object property', async () => {
    const operation = AutomatedTellerMachine.useCase.withdrawCash.relatedService.operations.find(
      ({name}) => name === 'withdrawCash'
    )!;
    const generated = await createEntryCode({
      project: 'AutomatedTellerMachine',
      useCase: 'withdrawCash',
      operation: operation.name,
      ocl: {
        definition: operation.definition,
        precondition: operation.precondition,
        postcondition: operation.postcondition,
      },
    });

    const diagnostics = parseTypescriptEntry(generated.entry);

    expect(diagnostics.filter(({code}) => code === 2362 || code === 2365)).toEqual([]);
  });

  test('typechecks numeric @pre expressions inside a collection iterator', async () => {
    const operation =
      LibraryManagementSystem.useCase.countDownSuspensionDay.relatedService.operations.find(
        ({name}) => name === 'countDownSuspensionDay'
      )!;
    const generated = await createEntryCode({
      project: 'LibraryManagementSystem',
      useCase: 'countDownSuspensionDay',
      operation: operation.name,
      ocl: {
        definition: operation.definition,
        precondition: operation.precondition,
        postcondition: operation.postcondition,
      },
    });

    const diagnostics = parseTypescriptEntry(generated.entry);

    expect(diagnostics.filter(({code}) => code === 2362 || code === 2365)).toEqual([]);
  });
});
