import {UseCase} from '@/rm2pt/model/UseCase';
import {GetOperationCodeParams, removeFileExportsAndImports} from './operationCodeShared';
import * as project from '@/rm2pt/project';
import {
  generateTypescriptEntityFile,
  generateTypescriptServiceFile,
} from './generateTypescriptCode';
import {formatTypescript} from '../util';
import generate from '@babel/generator';
import {Operation} from '@/rm2pt/model/Operation';
export const createEntryCode = async ({
  project: key,
  useCase: uc,
  operation: op,
  ocl,
}: GetOperationCodeParams & {
  ocl: Pick<Operation, 'definition' | 'precondition' | 'postcondition'>;
}) => {
  const p = project[key];
  const entity = p.entity;
  const useCase = p.useCase[uc as keyof typeof p.useCase] as UseCase;
  const service = {...useCase.relatedService};
  const newServiceName = `${service.name}_AutoGenerated`;
  if (service.useCase) {
    service.useCase = {...service.useCase};
    if (service.useCase.systemService) {
      service.useCase.systemService = {...service.useCase.systemService, name: newServiceName};
    }
  }
  const operation = service.operations.find((o) => o.name === op)!;
  const entityFile = generateTypescriptEntityFile(entity, service);
  service.name = newServiceName;
  const {file: serviceFile} = generateTypescriptServiceFile(service, [{...operation, ...ocl}]);
  const originalEntity = await formatTypescript(generate(entityFile).code);
  const originalService = await formatTypescript(
    generate(serviceFile).code.replaceAll(' End*/', ' End*/\n')
  );
  removeFileExportsAndImports(entityFile);
  removeFileExportsAndImports(serviceFile);
  const codes = {
    originalEntity,
    originalService,
    entity: await formatTypescript(generate(entityFile).code),
    service: await formatTypescript(generate(serviceFile).code.replaceAll(' End*/', ' End*/\n')),
  };
  return {
    ...codes,
    entry: buildEntryCode(codes),
  };
};

export const buildEntryCode = ({service, entity}: {service: string; entity: string}) => {
  return (
    [
      'import dayjs from "dayjs";',
      'import {l, PreconditionError, StandardOPs} from "../globalEntry";',
    ].join('\n') +
    `\n` +
    [entity, service].join('\n\n')
  );
};
