import * as babel from '@babel/core';
import generate from '@babel/generator';
// @ts-expect-error no types for this package
import presetTypescript from '@babel/preset-typescript';
import fs from 'fs-extra';
import * as jest from 'jest';
import path from 'path';
import {createEntryCode} from '@/app/service/createEntryCode';
import {createGlobalEntryCode} from '@/app/service/createGlobalEntryCode';
import * as projects from '@/rm2pt/project';

type GenerationFailure = {
  project: string;
  useCase: string;
  operation: string;
  error: string;
};

type TestFailure = {
  testFile: string;
  assertions: Array<{
    title: string;
    message: string;
  }>;
  suiteMessage?: string;
};

const testRoot = path.resolve(process.cwd(), 'test');
const temporaryRoot = path.resolve(testRoot, 'tmp', 'ocltsvm-hybrid');
const resultPath = path.resolve(process.cwd(), 'results', 'ocltsvm_hybrid_verification.json');

const resetTemporaryRoot = () => {
  const expectedParent = path.resolve(testRoot, 'tmp');
  if (!temporaryRoot.startsWith(`${expectedParent}${path.sep}`)) {
    throw new Error(`Refusing to reset unexpected path: ${temporaryRoot}`);
  }
  fs.removeSync(temporaryRoot);
  fs.ensureDirSync(temporaryRoot);
  fs.copySync(path.resolve(testRoot, 'helpers'), path.resolve(temporaryRoot, 'helpers'));
};

const adaptTest = (sourcePath: string, serviceName: string) => {
  const ast = babel.parse(fs.readFileSync(sourcePath, 'utf-8'), {
    filename: sourcePath,
    presets: [presetTypescript],
  })!;
  babel.traverse(ast, {
    enter(nodePath) {
      if (nodePath.isIdentifier({name: serviceName})) {
        nodePath.node.name = `${serviceName}_AutoGenerated`;
      }
    },
  });
  return generate(ast).code;
};

const compactMessage = (message: string | null | undefined) =>
  (message ?? '')
    .replace(/\u001b\[[0-9;]*m/g, '')
    .replace(/\r/g, '')
    .slice(0, 4000);

const main = async () => {
  resetTemporaryRoot();
  fs.writeFileSync(path.resolve(temporaryRoot, 'globalEntry.ts'), createGlobalEntryCode());

  let generatedOperations = 0;
  let executableOperations = 0;
  const generationFailures: GenerationFailure[] = [];

  const originalConsoleLog = console.log;
  console.log = () => undefined;
  try {
    for (const [projectName, project] of Object.entries(projects)) {
      for (const [useCaseName, useCase] of Object.entries(project.useCase)) {
        const service = useCase.relatedService;
        for (const operation of service.operations) {
          generatedOperations++;
          const sourceTest = path.resolve(
            testRoot,
            `${projectName}-${service.name}-${operation.name}`,
            'index.test.ts'
          );
          if (!fs.existsSync(sourceTest)) {
            continue;
          }

          try {
            const code = await createEntryCode({
              project: projectName as keyof typeof projects,
              useCase: useCaseName as never,
              operation: operation.name,
              ocl: {
                definition: operation.definition,
                precondition: operation.precondition,
                postcondition: operation.postcondition,
              },
            });
            const caseDirectory = path.resolve(
              temporaryRoot,
              `${projectName}-${useCaseName}-${service.name}-${operation.name}`
            );
            fs.ensureDirSync(caseDirectory);
            fs.writeFileSync(path.resolve(caseDirectory, 'entry.ts'), code.entry);
            fs.writeFileSync(
              path.resolve(caseDirectory, 'index.test.ts'),
              adaptTest(sourceTest, service.name)
            );
            executableOperations++;
          } catch (error) {
            generationFailures.push({
              project: projectName,
              useCase: useCaseName,
              operation: operation.name,
              error: error instanceof Error ? error.message : String(error),
            });
          }
        }
      }
    }
  } finally {
    console.log = originalConsoleLog;
  }

  const run = await jest.runCLI(
    {
      _: [],
      $0: 'verify-ocltsvm-hybrid',
      coverage: false,
      reporters: [],
      roots: [temporaryRoot],
      runInBand: true,
      silent: true,
    },
    [process.cwd()]
  );
  const testFailures: TestFailure[] = run.results.testResults
    .filter((suite) => suite.numFailingTests > 0 || suite.failureMessage)
    .map((suite) => ({
      testFile: path.relative(process.cwd(), suite.testFilePath),
      assertions: suite.testResults
        .filter((assertion) => assertion.status === 'failed')
        .map((assertion) => ({
          title: assertion.fullName,
          message: compactMessage(assertion.failureMessages.join('\n')),
        })),
      ...(suite.failureMessage ? {suiteMessage: compactMessage(suite.failureMessage)} : {}),
    }));
  const summary = {
    generatedOperations,
    executableOperations,
    generationFailures,
    testSuites: {
      passed: run.results.numPassedTestSuites,
      failed: run.results.numFailedTestSuites,
      total: run.results.numTotalTestSuites,
    },
    tests: {
      passed: run.results.numPassedTests,
      failed: run.results.numFailedTests,
      pending: run.results.numPendingTests,
      total: run.results.numTotalTests,
    },
    testFailures,
    success: generationFailures.length === 0 && run.results.success,
  };
  fs.ensureDirSync(path.dirname(resultPath));
  fs.writeJSONSync(resultPath, summary, {spaces: 2});
  process.stdout.write(
    `${JSON.stringify(
      {
        generatedOperations: summary.generatedOperations,
        executableOperations: summary.executableOperations,
        generationFailureCount: summary.generationFailures.length,
        testSuites: summary.testSuites,
        tests: summary.tests,
        testFailureCount: summary.testFailures.length,
        success: summary.success,
      },
      null,
      2
    )}\n`
  );
  if (!summary.success) {
    process.exitCode = 1;
  }
};

main().catch((error) => {
  const failure = {
    success: false,
    fatalError: error instanceof Error ? (error.stack ?? error.message) : String(error),
  };
  fs.ensureDirSync(path.dirname(resultPath));
  fs.writeJSONSync(resultPath, failure, {spaces: 2});
  console.error(failure.fatalError);
  process.exitCode = 1;
});
