import fs from 'fs-extra';
import * as jest from 'jest';
import path from 'path';
import {pathToFileURL} from 'url';
import {ContractSeparator} from '../src/app/ContractSeparator';
import {createEntryCode} from '../src/app/service/createEntryCode';
import {createGlobalEntryCode} from '../src/app/service/createGlobalEntryCode';

type Attempt = {
  operation_id?: string;
  model?: string;
  attempt?: number;
  syntax_valid?: boolean;
  extraction_success?: boolean;
  extracted_ocl?: string;
  contract?: string;
};

const operationId = 'AutomatedTellerMachine_checkBalance_checkBalance';
const attemptsPath = path.resolve(
  process.cwd(),
  'results/contractgen-study-v6/contract_gen/full_feedback/gpt-5.5/attempts.jsonl'
);
const temporaryRoot = path.resolve(process.cwd(), 'test/tmp/semantic-agreement-check-balance');
const caseRoot = path.resolve(temporaryRoot, 'case');

const argument = (name: string) => {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : '';
};

const score = (row: Attempt): [number, number, number, number] => [
  row.syntax_valid ? 1 : 0,
  row.extraction_success ? 1 : 0,
  row.extracted_ocl || row.contract ? 1 : 0,
  -Number(row.attempt || 999),
];

const greater = (left: number[], right: number[]) => {
  for (let index = 0; index < left.length; index++) {
    if (left[index] !== right[index]) return left[index] > right[index];
  }
  return false;
};

const selectedAttempt = () => {
  const attempts = fs
    .readFileSync(attemptsPath, 'utf-8')
    .split(/\r?\n/)
    .filter(Boolean)
    .map((line) => JSON.parse(line) as Attempt)
    .filter((row) => row.operation_id === operationId && row.model === 'gpt-5.5');
  if (!attempts.length) throw new Error(`No GPT-5.5 attempt found for ${operationId}`);
  return attempts.reduce((best, row) => (greater(score(row), score(best)) ? row : best));
};

const prepareGeneratedEntry = async () => {
  const attempt = selectedAttempt();
  const contract = attempt.extracted_ocl || attempt.contract || '';
  const separated = new ContractSeparator().separate(contract) as {
    definition?: string;
    precondition: string;
    postcondition: string;
  };
  const generated = await createEntryCode({
    project: 'AutomatedTellerMachine',
    useCase: 'checkBalance',
    operation: 'checkBalance',
    ocl: separated,
  });
  fs.removeSync(temporaryRoot);
  fs.ensureDirSync(caseRoot);
  fs.copySync(path.resolve(process.cwd(), 'test/helpers'), path.resolve(temporaryRoot, 'helpers'));
  fs.writeFileSync(path.resolve(temporaryRoot, 'globalEntry.ts'), createGlobalEntryCode());
  fs.writeFileSync(path.resolve(caseRoot, 'entry.ts'), generated.entry);
  return path.resolve(caseRoot, 'entry.ts');
};

const runOCLTSVM = async (scenario: string) => {
  const entryPath = await prepareGeneratedEntry();
  const runtime = await import(`${pathToFileURL(entryPath).href}?t=${Date.now()}`);
  const {AutomatedTellerMachineSystem_AutoGenerated, BankCard, getRepository} = runtime;
  getRepository(BankCard).splice(0);
  const service = new AutomatedTellerMachineSystem_AutoGenerated();
  const card = new BankCard();
  card.Balance = 9999;
  getRepository(BankCard).push(card);
  service.InputCard = card;
  service.CardIDValidated = true;
  service.PasswordValidated = scenario !== 'pre-negative';

  if (scenario === 'pre-negative') {
    let rejected = false;
    try {
      service.checkBalance();
    } catch (error) {
      rejected = error instanceof Error && error.constructor.name === 'PreconditionError';
    }
    if (!rejected || card.Balance !== 9999) {
      throw new Error('OCLTSVM did not reject the negative pre-state without mutation');
    }
    process.stdout.write('SEMANTIC_DECISION: false\n');
    return;
  }

  const before = card.Balance;
  const result = service.checkBalance();
  if (result !== 9999 || card.Balance !== before) {
    throw new Error('OCLTSVM violated the checkBalance post-state scenario');
  }
  process.stdout.write('SEMANTIC_DECISION: true\n');
};

const runJestOracle = async (scenario: string) => {
  await prepareGeneratedEntry();
  const sourceTest = fs.readFileSync(
    path.resolve(
      process.cwd(),
      'test/AutomatedTellerMachine-AutomatedTellerMachineSystem-checkBalance/index.test.ts'
    ),
    'utf-8'
  );
  fs.writeFileSync(
    path.resolve(caseRoot, 'index.test.ts'),
    sourceTest.replace(
      /\bAutomatedTellerMachineSystem\b/g,
      'AutomatedTellerMachineSystem_AutoGenerated'
    )
  );
  const testNamePattern =
    scenario === 'pre-negative'
      ? 'rejects when password is not validated'
      : 'Happy Path: returns current card balance without changing it';
  const execution = await jest.runCLI(
    {
      _: [],
      $0: 'semantic-agreement-check-balance',
      roots: [temporaryRoot],
      runInBand: true,
      silent: true,
      testNamePattern,
    },
    [process.cwd()]
  );
  if (!execution.results.success) {
    throw new Error(`Jest oracle failed for ${scenario}`);
  }
  process.stdout.write(`SEMANTIC_DECISION: ${scenario === 'pre-negative' ? 'false' : 'true'}\n`);
};

const main = async () => {
  const validator = argument('--validator');
  const scenario = argument('--scenario');
  if (!['pre-positive', 'pre-negative', 'post-positive'].includes(scenario)) {
    throw new Error(`Unsupported --scenario: ${scenario}`);
  }
  if (validator === 'ocltsvm') {
    await runOCLTSVM(scenario);
  } else if (validator === 'jest') {
    await runJestOracle(scenario);
  } else {
    throw new Error(`Unsupported --validator: ${validator}`);
  }
};

main().catch((error) => {
  console.error(error instanceof Error ? error.stack || error.message : String(error));
  process.exitCode = 1;
});
